//
// If not stated otherwise in this file or this component's LICENSE file the
// following copyright and licenses apply:
//
// Copyright 2025 Comcast Cable Communications Management, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/// Privileges specific to the Sky/Entos platform.
///
/// TODO: These will be removed from the public header in the future.

/// The app or service is requesting access to the AS services with the given
/// level. Only one of these privileges will be set at any given time.
///
/// In practical terms, this means the app or service can access AS on one
/// of its specified ports.
pub const ENTOS_AS_ACCESS_LEVEL1_PERMISSION: &str = "urn:entos:permission:as-access:level1";
pub const ENTOS_AS_ACCESS_LEVEL2_PERMISSION: &str = "urn:entos:permission:as-access:level2";
pub const ENTOS_AS_ACCESS_LEVEL3_PERMISSION: &str = "urn:entos:permission:as-access:level3";
pub const ENTOS_AS_ACCESS_LEVEL4_PERMISSION: &str = "urn:entos:permission:as-access:level4";
pub const ENTOS_AS_ACCESS_LEVEL5_PERMISSION: &str = "urn:entos:permission:as-access:level5";

/// The app or service is permitted to post intents to other apps or services
/// via the AS system.
pub const ENTOS_AS_POST_INTENT_PERMISSION: &str = "urn:entos:permission:as-access:post-intents";

/// The application requires access to the ASPlayer composition API. This
/// allows the app to control playback of A/V content generated by the ASPlayer.
///
/// Note: This privilege is only available on platforms that support the ASPlayer.
/// It is considered a legacy requirement; going forward, expect all video
/// surfaces to be handled in a more generic way.
///
/// Note: This doesn't control access to the ASPlayer REST API; this is
/// controlled by the `ASAccessLevelX` privileges.
pub const ENTOS_AS_PLAYER_PERMISSION: &str = "urn:entos:permission:as-player";

/// The application requires access to AirPlay services.
pub const ENTOS_AIRPLAY_PERMISSION: &str = "urn:entos:permission:airplay";

/// The application requires access to Chrome Cast services.
pub const ENTOS_CHROMECAST_PERMISSION: &str = "urn:entos:permission:chromecast";

/// The application requires the ability to request a bearer token from
/// the system for authentication to backend systems.
pub const ENTOS_BEARER_TOKEN_AUTHENTICATION_PERMISSION: &str = "urn:entos:permission:bearer-token-authentication";

/// The application requires the ability to access mTLS certificates
/// for authentication to backend systems.
pub const ENTOS_HTTPS_MTLS_AUTHENTICATION_PERMISSION: &str = "urn:entos:permission:https-mutual-authentication";

/// The application requires access to information on the current entitlements
/// set on the device.
///
/// This does not give the app access to modify the entitlements, just to
/// read the current entitlement information.
pub const ENTOS_ENTITLEMENT_INFO_PERMISSION: &str = "urn:entos:permission:entitlements:info";

/// \deprecated
/// Legacy permission used to denote special behaviour if the app was launched.
/// This is no longer used, but kept for backwards compatibility.
pub const ENTOS_MEMORY_INTENSIVE_PERMISSION: &str = "urn:entos:permission:memory-intensive";
