#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Unit Tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    name: Unit Tests (${{ matrix.cfg_release_channel }} on ${{ matrix.os }})

    env:
      CFG_RELEASE_CHANNEL: ${{ matrix.cfg_release_channel }}

    strategy:
      matrix:
        cfg_release_channel: [ "stable" ]
        os: [ "ubuntu-latest", "macos-latest" ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 2

      # Autotools is needed to build the erofs-utils C code
      - name: Install autotools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool

      - name: Install autotools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install autoconf automake libtool

      # Install rustup
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain ${{ matrix.cfg_release_channel }}

      # Verify rustup and cargo installation
      - name: Verify installation
        run: |
          . "$HOME/.cargo/env"
          rustup --version
          cargo --version

      # Cache the downloaded packages
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Run the tests
      - name: Run tests
        run: |
          . "$HOME/.cargo/env"
          cargo test --verbose
